### ISSUE TITLE
Running game gives error

### ISSUE THREAD

**Issue by tvmaaren** [bennibaermann/maximetro#1]
When I try to run the game with the following command:

> maximetro/maximetro.py 

I get the following output:

> Traceback (most recent call last):
  File "/tmp/maximetro/maximetro.py", line 16, in <module>
    from Util import *
  File "/tmp/maximetro/Util.py", line 113
    print string,
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(string, end=" ")?

I use python version 3.9.6

**Comment by sergi0g** [comment]
You should enclose the command in parentheses like this: print(string)
Hope that works for you! If you see any more related errors do the same. (By the way if you do not know how to find the file look at the error message and find the correct file and line which the error occurred in)

**Comment by tvmaaren** [comment]
Yes thanks. That solved the issue.
